development: &defaults
  adapter: mysql2
  database: jeff_development
  pool: 5
  username: root
  password: sanjay123
  host: localhost

test:
  <<: *defaults
  database: jeff_test

production:
  <<: *defaults
  database: jeff_prod